version: '3.8'

services:
  # service 1: Python Backend API
  web:
    build:
      context: ./backend
    # use .env file to set the environment parameter
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # TODO: 我的项目的架构应该是什么?
    # ensure the database start before the backend
    depends_on:
      - db
      - neo4j

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes: # TODO: 这个volume是放在我的本地还是docker?
      - postgres_data:/var/lib/postgresql/data
    environment: ## TODO: 这里可以直接读? 也就是说我的名字一定不能写错?
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  neo4j:
    image: neo4j:latest
    env_file:
      - .env
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_DEFAULT_DATABASE=${NEO4J_DATABASE}

volumes:
  postgres_data:
  neo4j_data:
