"""
Graph generation response schema.
"""
from pydantic import BaseModel, Field


class GraphGenerationResponse(BaseModel):
    """Response schema for graph generation from markdown."""

    graph_id: str = Field(..., description="Graph UUID")
    nodes_created: int = Field(..., description="Number of new nodes created")
    prerequisites_created: int = Field(
        ..., description="Number of prerequisite relationships created"
    )
    total_nodes: int = Field(..., description="Total nodes in graph after generation")
    max_level: int = Field(..., description="Maximum topological level in the graph")
    message: str = Field(..., description="Success message")


class RelationGenerationResponse(BaseModel):
    """Response schema for relation generation."""

    graph_id: str = Field(..., description="Graph UUID")
    edges_created: int = Field(..., description="Number of prerequisite edges created")
    edges_generated: int = Field(..., description="Total edges generated by LLM")
    bad_edges: int = Field(..., description="Edges with invalid node references")
    duplicate_edges: int = Field(..., description="Edges that already exist")
    cycle_edges: int = Field(..., description="Edges that would create cycles")
    nodes_updated: int = Field(
        ..., description="Number of nodes with updated topology"
    )
    max_level: int = Field(..., description="Maximum topological level in the graph")
    message: str = Field(..., description="Success message")

